version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    versioning-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'security'
    reviewers:
      - 'arijitchhatui'
    assignees:
      - 'arijitchhatui'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
