export const Collections = {
  USERS: 'users',
  USER_PROFILES: 'user_profiles',
  POSTS: 'posts',
  LIKES: 'likes',
  COMMENTS: 'comments',
  SAVES: 'saves',
  SHARES: 'shares',
  STORIES: 'stories',
  FOLLOWERS: 'followers',
  MESSAGES: 'messages',
  CHANNELS: 'channels',
  REELS: 'reels',
  PROFILES: 'profiles',
} as const;
