import { AssetsEntity } from '../entities/assets.entity';
import { ChannelsEntity } from '../entities/channels.entity';
import { CommentsEntity } from '../entities/comments.entity';
import { CreatorAssetsEntity } from '../entities/creator_assets.entity';
import { FanAssetsEntity } from '../entities/fan_assets.entity';
import { FollowersEntity } from '../entities/followers.entity';
import { GroupMessagesEntity } from '../entities/group-messages.entity';
import { GroupReactionsEntity } from '../entities/group-reactions.entity';
import { GroupRepliesEntity } from '../entities/group_replies.entity';
import { GroupsEntity } from '../entities/groups.entity';
import { LikesEntity } from '../entities/likes.entity';
import { MessagesEntity } from '../entities/messages.entity';
import { PaymentsEntity } from '../entities/payments.entity';
import { PostAssetsEntity } from '../entities/post_assets.entity';
import { PostsEntity } from '../entities/posts.entity';
import { PurchasesEntity } from '../entities/purchases.entity';
import { ReactionsEntity } from '../entities/reactions.entity';
import { ReelsEntity } from '../entities/reels.entity';
import { RepliesEntity } from '../entities/replies.entity';
import { SavesEntity } from '../entities/saves.entity';
import { SharesEntity } from '../entities/shares.entity';
import { StoriesEntity } from '../entities/stories.entity';
import { SubscriptionPlansEntity } from '../entities/subscription_plans.entity';
import { SubscriptionsEntity } from '../entities/subscriptions.entity';
import { UserProfilesEntity } from '../entities/user-profiles.entity';
import { UsersEntity } from '../entities/users.entity';
import { db } from '../rdb/mongodb';
import { Collections } from './constants';

export const userProfilesRepository = db.collection<UserProfilesEntity>(Collections.USER_PROFILES);
export const followersRepository = db.collection<FollowersEntity>(Collections.FOLLOWERS);
export const postsRepository = db.collection<PostsEntity>(Collections.POSTS);
export const likesRepository = db.collection<LikesEntity>(Collections.LIKES);
export const commentsRepository = db.collection<CommentsEntity>(Collections.COMMENTS);
export const savesRepository = db.collection<SavesEntity>(Collections.SAVES);
export const sharesRepository = db.collection<SharesEntity>(Collections.SHARES);
export const paymentsRepository = db.collection<PaymentsEntity>(Collections.PAYMENTS);
export const purchasesRepository = db.collection<PurchasesEntity>(Collections.PURCHASES);
export const usersRepository = db.collection<UsersEntity>(Collections.USERS);
export const messagesRepository = db.collection<MessagesEntity>(Collections.MESSAGES);
export const subscriptionsRepository = db.collection<SubscriptionsEntity>(Collections.SUBSCRIPTIONS);
export const subscriptionPlansRepository = db.collection<SubscriptionPlansEntity>(Collections.SUBSCRIPTION_PLANS);
export const fanAssetsRepository = db.collection<FanAssetsEntity>(Collections.FAN_ASSETS);
export const channelsRepository = db.collection<ChannelsEntity>(Collections.CHANNELS);
export const messageReactionsRepository = db.collection<ReactionsEntity>(Collections.REACTIONS);
export const groupsRepository = db.collection<GroupsEntity>(Collections.GROUPS);
export const groupMessagesRepository = db.collection<GroupMessagesEntity>(Collections.GROUP_MESSAGES);
export const groupReactionsRepository = db.collection<GroupReactionsEntity>(Collections.GROUP_REACTIONS);
export const repliesRepository = db.collection<RepliesEntity>(Collections.REPLIES);
export const groupRepliesRepository = db.collection<GroupRepliesEntity>(Collections.GROUP_REPLIES);
export const assetsRepository = db.collection<AssetsEntity>(Collections.ASSETS);
export const creatorAssetsRepository = db.collection<CreatorAssetsEntity>(Collections.CREATOR_ASSETS);
export const reelsRepository = db.collection<ReelsEntity>(Collections.REELS);
export const storiesRepository = db.collection<StoriesEntity>(Collections.STORIES);
export const postAssetsRepository = db.collection<PostAssetsEntity>(Collections.POST_ASSETS);
