name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          🎉 Welcome to the project! 🎉

          Congratulations on creating your first issue! You're officially part of the team now. 🚀

          Thank you for contributing to this project. Keep up the great work, and feel free to reach out if you have any questions.

          Happy coding! 😄
          
        pr-message: |
          🎉 Welcome to the project! 🎉

          Congratulations on creating your first pull request! You're officially part of the team now. 🚀

          Thank you for contributing to this project. Keep up the great work, and feel free to reach out if you have any questions.

          Happy coding! 😄"
